version: '2'
services:
    informix:
        image: "appiriodevops/informix:1b3d4ef"
        ports:
            - "2021:2021"
    dynamodb: 
        image: "tray/dynamodb-local"
        ports: 
            - "7777:7777"
        command: "-inMemory -port 7777"
    elasticsearch:
        image: "elasticsearch:2.3"
        ports:
            - "9200:9200"
            - "9300:9300"
    kafka:
        image: spotify/kafka
        environment:
            ADVERTISED_HOST: $DOCKER_IP
            ADVERTISED_PORT: 9092
        ports:
            - "2181:2181"
            - "9092:9092"
    redis:
        image: "redis:3.0.7"
        ports:
            - "6379:6379"
