workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "service/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install awscli
          command: sudo apt-get -y -qq install awscli

      - run:
          name: Building package
          command: mvn clean compile package -f service/pom.xml

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "service/pom.xml" }}
        
      # run tests!
      - run: mvn test -f service/pom.xml

  deploy_prod:
    steps:
      - run:
          name: Deploying master
          command: echo "This is a testing to deploy master branch."

