common_settings: &common_settings
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        MAVEN_OPTS: -Xmx3200m
  working_directory: ~/repo

restore_cache_settings: &restore_cache_settings
  keys:
    - tc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "service/pom.xml" }}
    - tc-{{ .Environment.CIRCLE_JOB }}-

save_cache_settings: &save_cache_settings
  key: tc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "service/pom.xml" }}
  paths:
    - ~/.m2
    - ~/repo/service/target/member-microservice*.jar

version: 2
jobs:
  build:
    <<: *common_settings
    steps:
      - checkout
      - restore_cache: *restore_cache_settings
      - run:
          name: Install awscli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Building Package
          command: mvn clean compile package -f service/pom.xml
      - save_cache: *save_cache_settings

  deploy_prod:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - tc-build-{{ .Branch }}-{{ checksum "service/pom.xml" }}
            - tc-build-
      - run:
          name: Deploying master
          command: |
            echo $CIRCLE_BUILD_NUM
            .deploy/test_deploy_master.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: master

