####################
# Templates
####################
common_settings: &common_settings
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/repo

restore_cache_settings: &restore_cache_settings
  keys:
    - tc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "service/pom.xml" }}
    - tc-{{ .Environment.CIRCLE_JOB }}-

restore_cache_settings_for_build: &restore_cache_settings_for_build
  keys:
    - tc-build-{{ .Branch }}-{{ checksum "service/pom.xml" }}
    - tc-build-

save_cache_settings: &save_cache_settings
  key: tc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "service/pom.xml" }}
  paths:
    - ~/.m2
    - ~/repo/service/target/member-microservice*.jar

install_aws: &install_aws
  name: Install awscli
  command: pip install awsebcli


####################
# Jobs
####################
version: 2
jobs:
  build:
    <<: *common_settings
    steps:
      - checkout
      - restore_cache: *restore_cache_settings
      - run:
          name: Building Package
          command: mvn clean compile package -f service/pom.xml
      - save_cache: *save_cache_settings

  deploy_prod:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore_cache_settings_for_build
      - run: *install_aws
      - run:
          name: Deploying MASTER
          command: |
            echo $CIRCLE_BUILD_NUM
            .deploy/test_deploy_master.sh
#            .deploy/dockerhub_push.sh PROD $CIRCLE_BUILD_NUM

  deploy_dev:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore_cache_settings_for_build
      - run: *install_aws
      - run:
          name: Deploying DEV
          command: |
            echo $CIRCLE_BUILD_NUM
            .deploy/dockerhub_push.sh DEV $CIRCLE_BUILD_NUM


####################
# Workflows
####################
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - feature/circleci
